### PR TITLE
fix(basti-cdk): Add required IAM permission

### PR DESCRIPTION
**Pull request by bobveringa**
During more testing with the rest of my team I found that I forgot to add the permission that allows `arn:aws:ssm:*:*:document/AWS-StartPortForwardingSessionToRemoteHost`. This wasn't an issue for the initial roles I tested it with because they were granted this permissions by some other policy.

### CODE REVIEW

**Comment by BohdanPetryshyn** [comment]
I just noticed this when was testing `basti-cdk` with the test CDK app: https://github.com/BohdanPetryshyn/basti/pull/55/files#diff-b5a46dba7e3da24b7e9a6416e5dd8cc03c8ca8399d5ac09dc942d8aa71faa1fbR175

**Comment by BohdanPetryshyn** [comment]
But I haven't fixed it yet, just left a `FIXME` there. This PR definitely makes sense and has to be merged

**Comment by BohdanPetryshyn** [comment]
@bobveringa Could you please implement the policies the same way as described [here](https://github.com/BohdanPetryshyn/basti/tree/feat/basti-cdk#minimal-iam-permissions)? Just in case.

**Comment by bobveringa** [comment]
@BohdanPetryshyn With this PR they should be the same right?

**Comment by BohdanPetryshyn** [comment]
@bobveringa I can no longer see the changed files, but I remember that the SSM Document resource was added to EC2 and SSM actions while the README only adds the resource to the `ssm:StartSession` action

**Pull request closed without merging**
